/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopperRouteImport } from './routes/shopper'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as IndexRouteImport } from './routes/index'

const ShopperRoute = ShopperRouteImport.update({
  id: '/shopper',
  path: '/shopper',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchant': typeof MerchantRoute
  '/our-story': typeof OurStoryRoute
  '/shopper': typeof ShopperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchant': typeof MerchantRoute
  '/our-story': typeof OurStoryRoute
  '/shopper': typeof ShopperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merchant': typeof MerchantRoute
  '/our-story': typeof OurStoryRoute
  '/shopper': typeof ShopperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/merchant' | '/our-story' | '/shopper'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/merchant' | '/our-story' | '/shopper'
  id: '__root__' | '/' | '/merchant' | '/our-story' | '/shopper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchantRoute: typeof MerchantRoute
  OurStoryRoute: typeof OurStoryRoute
  ShopperRoute: typeof ShopperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopper': {
      id: '/shopper'
      path: '/shopper'
      fullPath: '/shopper'
      preLoaderRoute: typeof ShopperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchantRoute: MerchantRoute,
  OurStoryRoute: OurStoryRoute,
  ShopperRoute: ShopperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
