/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopperRouteImport } from './routes/shopper'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CouncilOfStewardsRouteImport } from './routes/council-of-stewards'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationBodyRouteImport } from './routes/certification-body'
import { Route as IndexRouteImport } from './routes/index'

const ShopperRoute = ShopperRouteImport.update({
  id: '/shopper',
  path: '/shopper',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilOfStewardsRoute = CouncilOfStewardsRouteImport.update({
  id: '/council-of-stewards',
  path: '/council-of-stewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationBodyRoute = CertificationBodyRouteImport.update({
  id: '/certification-body',
  path: '/certification-body',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certification-body': typeof CertificationBodyRoute
  '/contact': typeof ContactRoute
  '/council-of-stewards': typeof CouncilOfStewardsRoute
  '/faq': typeof FaqRoute
  '/merchant': typeof MerchantRoute
  '/our-story': typeof OurStoryRoute
  '/shopper': typeof ShopperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certification-body': typeof CertificationBodyRoute
  '/contact': typeof ContactRoute
  '/council-of-stewards': typeof CouncilOfStewardsRoute
  '/faq': typeof FaqRoute
  '/merchant': typeof MerchantRoute
  '/our-story': typeof OurStoryRoute
  '/shopper': typeof ShopperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certification-body': typeof CertificationBodyRoute
  '/contact': typeof ContactRoute
  '/council-of-stewards': typeof CouncilOfStewardsRoute
  '/faq': typeof FaqRoute
  '/merchant': typeof MerchantRoute
  '/our-story': typeof OurStoryRoute
  '/shopper': typeof ShopperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certification-body'
    | '/contact'
    | '/council-of-stewards'
    | '/faq'
    | '/merchant'
    | '/our-story'
    | '/shopper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certification-body'
    | '/contact'
    | '/council-of-stewards'
    | '/faq'
    | '/merchant'
    | '/our-story'
    | '/shopper'
  id:
    | '__root__'
    | '/'
    | '/certification-body'
    | '/contact'
    | '/council-of-stewards'
    | '/faq'
    | '/merchant'
    | '/our-story'
    | '/shopper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificationBodyRoute: typeof CertificationBodyRoute
  ContactRoute: typeof ContactRoute
  CouncilOfStewardsRoute: typeof CouncilOfStewardsRoute
  FaqRoute: typeof FaqRoute
  MerchantRoute: typeof MerchantRoute
  OurStoryRoute: typeof OurStoryRoute
  ShopperRoute: typeof ShopperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopper': {
      id: '/shopper'
      path: '/shopper'
      fullPath: '/shopper'
      preLoaderRoute: typeof ShopperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council-of-stewards': {
      id: '/council-of-stewards'
      path: '/council-of-stewards'
      fullPath: '/council-of-stewards'
      preLoaderRoute: typeof CouncilOfStewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification-body': {
      id: '/certification-body'
      path: '/certification-body'
      fullPath: '/certification-body'
      preLoaderRoute: typeof CertificationBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificationBodyRoute: CertificationBodyRoute,
  ContactRoute: ContactRoute,
  CouncilOfStewardsRoute: CouncilOfStewardsRoute,
  FaqRoute: FaqRoute,
  MerchantRoute: MerchantRoute,
  OurStoryRoute: OurStoryRoute,
  ShopperRoute: ShopperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
